# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production website build & deployment

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Enable Notion data cache
        uses: actions/cache@v3
        with:
          key: notion-data-cache
          path: ./cache

      - name: Enable Notion files cache
        uses: actions/cache@v3
        with:
          key: notion-files-cache
          path: ./static

      - name: Install dependencies
        run: npm i

      - name: Download and cache Notion data
        run: |
          node node_modules/nebula-genesis/build/index.js \
            NOTION_TOKEN=${{ secrets.NOTION_TOKEN }} \
            DATABASE_ID=${{ secrets.DATABASE_ID }} \
            SITE_FOLDER_PATH=. \
            CACHE_FOLDER_NAME=pages \
            ON_OR_AFTER=${{ vars.ON_OR_AFTER }} \
            FILTERS='[{ "property": "Contexte", "select": { "equals": "Page" } }]'
          node node_modules/nebula-genesis/build/index.js \
            NOTION_TOKEN=${{ secrets.NOTION_TOKEN }} \
            DATABASE_ID=${{ secrets.DATABASE_ID }} \
            SITE_FOLDER_PATH=. \
            CACHE_FOLDER_NAME=articles \
            REINIT_CACHE=${{ vars.REINIT_CACHE }} \
            ON_OR_AFTER=${{ vars.ON_OR_AFTER }} \
            FILTERS='[{ "property": "Contexte", "select": { "equals": "Contenu" } }]'

      - name: Build website
        run: npx gatsby build

      - name: FTP prod environment
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./public
          remoteDir: ${{ secrets.FTP_PROD_DIR }}
